title: "Biovega Services"
description: "Official documentation for Biovega d.o.o. digital services"

# GitHub Pages URL configuration
url: "http://doc.platform.biovega.hr"
baseurl: "/"   # MUST match your repo name exactly

# logo: "/assets/images/biovegaservices.png"

# Theme
remote_theme: just-the-docs/just-the-docs

# Just the Docs configuration
just_the_docs:
  custom_css:
    - "/assets/css/custom.css"  # Optional custom CSS file if you create it

# Navigation & search
search_enabled: true
nav_sort: case_insensitive
color_scheme: light